name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SYSTEM_CONSTS: system_consts.cfg
  CALIBRATION_FILE: calibrationFile
  KEYS_TO_COMPARE: HARDWARE_FINGERPRINT
  DEFAULT: default
  AUTHENTICATOR: http://uv-authenticator.uveye.svc.cluster.local:3000/auth-data

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -r requirements-dev.txt


    - name: Run tests
      run: |
        python -m unittest discover -p '*_test.py'

